name: rodo
description: Automate dining experiences

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  flutter_launcher_icons: ^0.9.1
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  firebase_storage: ^10.0.1
  firebase_app_check: ^0.0.2
  cloud_firestore: ^2.4.0
  country_code_picker: ^2.0.2
  carousel_slider: ^4.0.0
  map: ^1.0.0
  cached_network_image: ^3.1.0
  geolocator: ^7.6.2
  google_maps_flutter: ^2.0.11
  dio: ^4.0.0
  flutter_polyline_points: ^1.0.0
  photo_view: ^0.13.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/resto_image_ios_switch.png"
  adaptive_icon_foreground: "assets/icons/resto_image_android_switch.png"
  adaptive_icon_background: "#FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
  uses-material-design: true
