name: rodoo
description: Dining without hassle

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  photo_view: ^0.14.0
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.1.0
  firebase_core: ^2.3.0
  dropdown_button2: ^1.9.1
  syncfusion_flutter_datepicker: ^20.3.60
  camera: ^0.10.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0
  firebase_auth: ^4.1.3
  firebase_storage: ^11.0.6
  firebase_app_check: ^0.1.1+5
  country_code_picker: ^2.0.2
  cached_network_image: ^3.1.0

flutter:
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/resto_image_ios_switch.png"
  adaptive_icon_foreground: "assets/icons/resto_image_android_switch.png"
  adaptive_icon_background: "#FFFFFF"
